services:
  mwn-db:
    image: postgres:18-alpine
    restart: on-failure
    volumes:
      - postgres-streamlit-db:/var/lib/postgresql
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}
    expose:
     - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  streamlit-application-con:
    image: ayooluwa29/streamlitapplication:v3
    restart: on-failure
    env_file:
     - .env
    depends_on:
     - mwn-db
    # expose:
    #  - 8501
    ports:
    - 8503:8501

volumes:
  postgres-streamlit-db: